### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by bQvle** [i4004/Simplify#104]
Is it possible to add additional headers to the email?

Like list-unsubscribe: http://www.list-unsubscribe.com/

> From: josh@domain.com
> Subject: [espc-tech] More info on List-Unsubscribe
> Date: August 31, 2006 3:13:02 PM CDT
> To: jasmine@domain.com
> List-Unsubscribe: <mailto:unsubscribe-espc-tech-12345N@domain.com>, <http://domain.com/member/unsubscribe/?listname=espc-tech@domain.com?id=12345N>

**Comment by i4004** [comment]
Yes, we have method which receives a standard system `System.Net.Mail.MailMessage` object, which contains `Headers` property you can use.
