### ISSUE TITLE
hi,can add a new mail setting key - MailFrom?

### ISSUE THREAD

**Issue by liufajian** [i4004/Simplify#57]
I use this mail sender in ours system to notify our the system's status ,but meet this trouble -- 
mail service provider return this fail message: Mail from must equal authorized user.

do you want to provide a default MailFrom setting in <MailSenderSettings> section, we have our own config section to provide MailFrom value,but i think it is better to get this value from <MailSenderSettings>.

thanks

**Comment by liufajian** [comment]
sorry，now  i think it is better to get this value from  our config section,we also need to config mailTo.
maybe you can delete this issue~~~

**Comment by i4004** [comment]
Hello! Yes, it is better to use you own config section for such kind of values.
