### ISSUE TITLE
Make SmtpUserName & Password Optional

### ISSUE THREAD

**Issue by pietervp** [i4004/Simplify#64]
Using the SmtpClientCurrentUser is not very practical at the moment. At a client we don't want to set the UserName & Password in config, but use the Windows Service User Account as identity to send mails. The only workaround is to provide a dummy user and password. 

The best way would be to use the SmtpClientCurrentUser when no credentials are provided in the config.

**Comment by i4004** [comment]
Please check 536bc1d, now SmtpUserName and SmtpUserPassword are optional parameters.
If they are not set in config, then default credentials will be used. If it is ok then i will release a package.
