### ISSUE TITLE
Assigning password from code, or encrypted from config file

### ISSUE THREAD

**Issue by nbelley** [i4004/Simplify#66]
As of right now, I can't find a way to specify the user or password to use with code, only from config file. It is not the best to have password in plain text in config file. Can you make it possible to create a setting object in the code, or at least modify the password from the default mail sender?

**Comment by i4004** [comment]
I can create a constructor for `MailSender` class with all that parameters from config file, then yon can pass any values you want without a config file

For default instance I can allow `Settings` property.to be set via property injection, then you can create and inject your custom implementation of `IMailSenderSettings` to default `MailSender` instance.

Originally this library was created for windows-service applications or any applications which runs on a servers, so nobody should have access to config file except from system administrations etc. So it is easy then maintain connection parameters from config file.

**Comment by nbelley** [comment]
Both are great ideas. For me it is a server side application, but a web one, and I just want to make sure that the mail account password is not seen by someone who has access to the web.config folder.

Thanks for looking into that!
