### ISSUE TITLE
The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by haamaanaa** [i4004/Simplify#92]
While trying to configure this framework to use our smtp server, this error was received from smtp server:

"The remote certificate is invalid according to the validation procedure."

Apparently the client calling the server needs to inform that it will trust the certificate, but I don't see this kind of option in the settings for MailSender class. Is there something for this?

**Comment by i4004** [comment]
@haamaanaa HI! there is no such option in the settings, but you can try something like this: http://stackoverflow.com/questions/777607/the-remote-certificate-is-invalid-according-to-the-validation-procedure-using

**Comment by haamaanaa** [comment]
It was my fault... i used IP address instead of domain name, so the certificate wasnt found correctly. But thanks for fast response!

**Comment by i4004** [comment]
Np :)
